---
- name: Install yum-utils
  yum:
    name: yum-utils
    state: present
- name: install openresty repo
  yum_repository:
    name: openresty
    description: OpenResty Repo (nginx with lua)
    baseurl: https://openresty.org/package/centos/7/x86_64
    gpgkey: https://openresty.org/package/pubkey.gpg

- name: Install openresty
  yum:
    name: openresty
    state: latest

- name: Install nginx binary
  file:
    src: /usr/local/openresty/nginx/sbin/nginx
    dest: /usr/sbin/nginx
    state: link

- name: create nginx group
  group: name=nginx system=true

- name: create nginx user
  user: name=nginx system=true group=nginx

- name: create default config in /etc/nginx
  file:
    src: /usr/local/openresty/nginx/conf
    dest: /etc/nginx
    state: link

